//! Staleness guards for `docs/CONFORMANCE.md`, the crate's public
//! conformance matrix (Annex A).
//!
//! That document is written for outside implementers to audit this crate's
//! conformance claim against, and a hand-authored matrix rots into a lie the
//! moment the code moves past it. These two tests are the anchor: the matrix
//! is generated by nobody, so the compiler cannot keep it honest — but the
//! test suite can keep it *complete* (every requirements class is covered)
//! and *truthful about its evidence* (every test it names exists).

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use rusty_cdb::conformance::RequirementsClass;

/// The matrix document, read from the crate root.
fn matrix() -> String {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("docs/CONFORMANCE.md");
    fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("{} must be readable: {error}", path.display()))
}

/// Every `.rs` file in the crate, sources and integration tests alike.
fn rust_sources() -> Vec<PathBuf> {
    fn walk(dir: &Path, found: &mut Vec<PathBuf>) {
        for entry in fs::read_dir(dir).expect("readable directory") {
            let path = entry.expect("readable entry").path();
            if path.is_dir() {
                walk(&path, found);
            } else if path.extension().is_some_and(|ext| ext == "rs") {
                found.push(path);
            }
        }
    }

    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mut found = Vec::new();
    walk(&root.join("src"), &mut found);
    walk(&root.join("tests"), &mut found);
    found
}

/// Annex A — the matrix covers **every** requirements class the crate
/// defines. A class added post-1.0 (the enum is `#[non_exhaustive]` for
/// exactly that reason) fails this test until the document grows the
/// section that audits it, so the matrix cannot silently fall behind the
/// conformance claim it documents.
#[test]
fn req_core_conformance_matrix_lists_every_requirements_class() {
    let document = matrix();
    for class in RequirementsClass::ALL {
        // Backticked, so the class must appear as a token of its own — the
        // §3 class-table row. A bare substring search would pass on
        // `versioning` merely because `/req/core/versioning` is in the file,
        // and on `geometry` because `/req/core/geometry-types` is.
        assert!(
            document.contains(&format!("`{}`", class.as_str())),
            "docs/CONFORMANCE.md does not list the {class} class as `{}`",
            class.as_str()
        );
        assert!(
            document.contains(&format!("`{}`", class.requirements_uri())),
            "docs/CONFORMANCE.md does not cite {}'s requirements URI `{}`",
            class,
            class.requirements_uri()
        );
    }
    assert!(
        document.contains("/conf/minimal-core"),
        "docs/CONFORMANCE.md must cite Annex A's mandatory bundle"
    );
}

/// The matrix's evidence column names real tests. Every backticked
/// `req_*`/`rec_*`/`conf_*`/`per_*` token in the document must resolve to a
/// test function in the crate — otherwise an audit follows a citation to a
/// test that was renamed or deleted, which is worse than no citation.
#[test]
fn req_core_conformance_matrix_cites_only_real_tests() {
    let mut defined: BTreeSet<String> = BTreeSet::new();
    for path in rust_sources() {
        let source = fs::read_to_string(&path).expect("readable source");
        for line in source.lines() {
            let trimmed = line.trim_start();
            if let Some(rest) = trimmed.strip_prefix("fn ")
                && let Some(name) = rest.split('(').next()
                && is_test_name(name)
            {
                defined.insert(name.to_owned());
            }
        }
    }
    assert!(
        defined.len() > 200,
        "the source scan found only {} test functions; the guard is not looking where it thinks",
        defined.len()
    );

    let document = matrix();
    let mut cited = 0usize;
    for (index, token) in document.split('`').enumerate() {
        // Odd-indexed fragments are the ones between backticks.
        if index % 2 == 1 && is_test_name(token) {
            cited += 1;
            assert!(
                defined.contains(token),
                "docs/CONFORMANCE.md cites `{token}`, which is not a test in this crate"
            );
        }
    }
    assert!(
        cited > 50,
        "the matrix cites only {cited} tests; it is not the evidence table it claims to be"
    );
}

/// Does `name` look like one of this crate's test functions (TDD_PLAN §5's
/// naming convention: a spec-prefixed, snake-case identifier)?
fn is_test_name(name: &str) -> bool {
    ["req_", "rec_", "conf_", "per_"]
        .iter()
        .any(|prefix| name.starts_with(prefix))
        && name
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
}
