//! Staleness guards for `docs/CONFORMANCE.md`, the crate's public
//! conformance matrix (Annex A).
//!
//! That document is written for outside implementers to audit this crate's
//! conformance claim against, and a hand-authored matrix rots into a lie the
//! moment the code moves past it. These three tests are the anchor: the
//! matrix is generated by nobody, so the compiler cannot keep it honest —
//! but the test suite can keep it *complete* (every requirements class is
//! covered), *truthful about its evidence* (every test it names exists and
//! is a real `#[test]`), and *truthful about its API column* (every crate
//! item it names exists).
//!
//! The matrix's premise is that a reader can follow a row to the code. Both
//! of its columns are therefore load-bearing, and both are guarded: the
//! Tests column since this document was written, the API column since a
//! review found `metadata::temporal::TemporalInterval` — a type that was
//! never written — sitting in it, which was exactly the dead end the
//! document exists to prevent.

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use opencdb::conformance::RequirementsClass;

/// The matrix document, read from the crate root.
fn matrix() -> String {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("docs/CONFORMANCE.md");
    fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("{} must be readable: {error}", path.display()))
}

/// Every `.rs` file under one directory of the crate.
fn rust_files(subdir: &str) -> Vec<PathBuf> {
    fn walk(dir: &Path, found: &mut Vec<PathBuf>) {
        for entry in fs::read_dir(dir).expect("readable directory") {
            let path = entry.expect("readable entry").path();
            if path.is_dir() {
                walk(&path, found);
            } else if path.extension().is_some_and(|ext| ext == "rs") {
                found.push(path);
            }
        }
    }

    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mut found = Vec::new();
    walk(&root.join(subdir), &mut found);
    found
}

/// Sources and integration tests alike — where a cited **test** may live.
fn rust_sources() -> Vec<PathBuf> {
    let mut found = rust_files("src");
    found.extend(rust_files("tests"));
    found
}

/// Annex A — the matrix covers **every** requirements class the crate
/// defines. A class added post-1.0 (the enum is `#[non_exhaustive]` for
/// exactly that reason) fails this test until the document grows the
/// section that audits it, so the matrix cannot silently fall behind the
/// conformance claim it documents.
#[test]
fn req_core_conformance_matrix_lists_every_requirements_class() {
    let document = matrix();
    for &class in RequirementsClass::ALL {
        // Backticked, so the class must appear as a token of its own — the
        // §3 class-table row. A bare substring search would pass on
        // `versioning` merely because `/req/core/versioning` is in the file,
        // and on `geometry` because `/req/core/geometry-types` is.
        assert!(
            document.contains(&format!("`{}`", class.as_str())),
            "docs/CONFORMANCE.md does not list the {class} class as `{}`",
            class.as_str()
        );
        assert!(
            document.contains(&format!("`{}`", class.requirements_uri())),
            "docs/CONFORMANCE.md does not cite {}'s requirements URI `{}`",
            class,
            class.requirements_uri()
        );
    }
    assert!(
        document.contains("/conf/minimal-core"),
        "docs/CONFORMANCE.md must cite Annex A's mandatory bundle"
    );
}

/// The matrix's evidence column names real tests. Every backticked
/// `req_*`/`rec_*`/`conf_*`/`per_*` token in the document must resolve to a
/// test function in the crate — otherwise an audit follows a citation to a
/// test that was renamed or deleted, which is worse than no citation.
#[test]
fn req_core_conformance_matrix_cites_only_real_tests() {
    let mut defined: BTreeSet<String> = BTreeSet::new();
    for path in rust_sources() {
        let source = fs::read_to_string(&path).expect("readable source");
        // A one-line lookback for the attribute: a citation must resolve to
        // something `cargo test` actually runs. Matching any `fn` with a
        // test-shaped name would let an ordinary helper stand in for the
        // evidence a row claims, which is the failure the guard exists to
        // catch — the name is not the proof, the `#[test]` is.
        let mut annotated = false;
        for line in source.lines() {
            let trimmed = line.trim_start();
            if let Some(rest) = trimmed.strip_prefix("fn ")
                && let Some(name) = rest.split('(').next()
                && is_test_name(name)
            {
                if annotated {
                    defined.insert(name.to_owned());
                }
                annotated = false;
                continue;
            }
            // `#[test]` may be followed by other attributes (`#[should_panic]`,
            // `#[ignore]`) before the `fn`, so the flag survives them.
            if trimmed.starts_with("#[test]") {
                annotated = true;
            } else if !trimmed.starts_with("#[") && !trimmed.is_empty() {
                annotated = false;
            }
        }
    }
    assert!(
        defined.len() > 200,
        "the source scan found only {} test functions; the guard is not looking where it thinks",
        defined.len()
    );
    // The scan's own decoy: a test-shaped name that is not a test. If the
    // lookback is ever loosened back to "any `fn` with a test prefix" this
    // enters the set and the guard stops proving what it claims.
    assert!(
        !defined.contains("req_core_conformance_matrix_decoy_is_not_a_test"),
        "the guard accepted a non-`#[test]` function as evidence"
    );

    let document = matrix();
    let mut cited = 0usize;
    for (index, token) in document.split('`').enumerate() {
        // Odd-indexed fragments are the ones between backticks.
        if index % 2 == 1 && is_test_name(token) {
            cited += 1;
            assert!(
                defined.contains(token),
                "docs/CONFORMANCE.md cites `{token}`, which is not a test in this crate"
            );
        }
    }
    assert!(
        cited > 50,
        "the matrix cites only {cited} tests; it is not the evidence table it claims to be"
    );
}

/// Not a test, deliberately: a test-shaped name carrying no `#[test]`, so
/// `req_core_conformance_matrix_cites_only_real_tests` can prove its
/// attribute lookback rather than assume it. Never cite this from the matrix.
#[allow(dead_code)]
fn req_core_conformance_matrix_decoy_is_not_a_test() {}

/// Every identifier this crate *defines* in `src/`: type, trait, function,
/// module, constant, struct field and enum variant names. Deliberately a
/// flat name set rather than a resolved path graph — the matrix's API column
/// cites items by qualified path, and the question the guard answers is
/// "does every segment of that path name something this crate actually
/// declares", which is what catches a renamed or never-written type.
fn defined_identifiers() -> BTreeSet<String> {
    let item = regex_free_item_names;
    let mut defined = BTreeSet::new();
    for path in rust_files("src") {
        let source = fs::read_to_string(&path).expect("readable source");
        for line in source.lines() {
            item(line.trim_start(), &mut defined);
        }
    }
    defined
}

/// Pulls the identifiers a single source line declares. Hand-rolled rather
/// than regex-driven: the crate carries no regex dependency, and the shapes
/// that matter are few.
fn regex_free_item_names(line: &str, into: &mut BTreeSet<String>) {
    const KEYWORDS: [&str; 8] = [
        "fn ", "struct ", "enum ", "trait ", "type ", "const ", "static ", "mod ",
    ];
    // `pub`, `pub(crate)`, `pub(super)`, `pub(in …)` prefixes, then `unsafe`,
    // `async` and the like: strip words until an item keyword is reached.
    let mut rest = line;
    loop {
        if let Some(keyword) = KEYWORDS.iter().find(|keyword| rest.starts_with(*keyword)) {
            let name: String = rest[keyword.len()..]
                .chars()
                .take_while(|c| c.is_alphanumeric() || *c == '_')
                .collect();
            if !name.is_empty() {
                into.insert(name);
            }
            return;
        }
        match rest.split_once(' ') {
            Some((head, tail))
                if matches!(head, "pub" | "unsafe" | "async" | "default")
                    || head.starts_with("pub(") =>
            {
                rest = tail.trim_start();
            }
            _ => break,
        }
    }
    // An enum variant (`Name,` / `Name {…}` / `Name(…)`) or a struct field
    // (`name: Type,`). Both are declarations the API column may cite, and a
    // variant's own inline fields are declarations too.
    let head: String = line
        .chars()
        .take_while(|c| c.is_alphanumeric() || *c == '_')
        .collect();
    if !head.is_empty() {
        let tail = line[head.len()..].trim_start();
        let is_variant =
            head.starts_with(|c: char| c.is_ascii_uppercase()) && tail.starts_with(['{', '(', ',']);
        let is_field = head.starts_with(|c: char| c.is_ascii_lowercase() || c == '_')
            && tail.starts_with(':')
            && !tail.starts_with("::");
        if is_variant || is_field {
            into.insert(head.clone());
        }
    }
    // Fields written inline inside a variant's braces: `Name { a: T, b: U }`.
    if let Some((_, body)) = line.split_once('{') {
        for field in body.split(',') {
            if let Some((name, _)) = field.split_once(':') {
                let name = name.trim();
                if !name.is_empty()
                    && name.starts_with(|c: char| c.is_ascii_lowercase() || c == '_')
                    && name.chars().all(|c| c.is_alphanumeric() || c == '_')
                {
                    into.insert(name.to_owned());
                }
            }
        }
    }
}

/// Backticked tokens in the API column that are **not** Rust items of this
/// crate and are not meant to be: spec metadata element names, WKT-2
/// keywords, `serde`'s own traits, and a file extension. Each is spelled
/// here rather than pattern-excluded so that adding one is a deliberate act
/// — a new unresolvable token fails the guard until someone says why.
const NON_CRATE_API_TOKENS: [&str; 9] = [
    // §7.9.4.2 conditional element names, as they appear on the wire.
    "domainSet",
    "windingOrder",
    "tilingScheme",
    // ISO 19162 WKT-2 keywords the CRS reader accepts or rejects (§7.3).
    "GEOGCRS",
    "GEODCRS",
    "VERTCRS",
    "COMPOUNDCRS",
    // `serde`'s traits, implemented here but declared there.
    "Serialize",
    "Deserialize",
];

/// The matrix's **API** column names real items of this crate. Every
/// backticked Rust-path token in it must resolve, segment by segment, to
/// something `src/` declares.
///
/// The Tests column has been guarded since the document was written; this
/// column was not, and a review found `metadata::temporal::TemporalInterval`
/// in it — a type that never existed (the real one is
/// `metadata::temporal::Temporal`, whose `Interval` arm is Metadata7's
/// subject). A row that dead-ends is worse for an auditor than no row: it
/// costs them the search before they learn the claim was never checkable.
#[test]
fn req_core_conformance_matrix_cites_only_real_api_items() {
    let defined = defined_identifiers();
    assert!(
        defined.len() > 500,
        "the source scan found only {} identifiers; the guard is not looking where it thinks",
        defined.len()
    );

    let document = matrix();
    let mut checked = 0usize;
    // §4 only. It is the sole section whose tables are
    // `| Requirement | Code | API | Tests |`; §5.1's and §7's third columns
    // are prose, where a backticked `gpkg` or `xml` is an encoding name, not
    // a promise that the crate declares an item by that name.
    let mut in_matrix = false;
    for line in document.lines() {
        if line.starts_with("## ") {
            in_matrix = line.starts_with("## 4.");
        }
        // Matrix rows only: `| Requirement | Code | API | Tests |`.
        if !in_matrix || !line.starts_with('|') {
            continue;
        }
        let cells: Vec<&str> = line.split('|').collect();
        if cells.len() < 5 {
            continue;
        }
        for (index, token) in cells[3].split('`').enumerate() {
            if index % 2 == 0 {
                continue;
            }
            // `apply_collection[_at]` names one item with an optional
            // suffix; the bracketed form resolves once flattened.
            let token = token.replace(['[', ']'], "");
            if !is_rust_path(&token) || NON_CRATE_API_TOKENS.contains(&token.as_str()) {
                continue;
            }
            checked += 1;
            for segment in token.split("::") {
                assert!(
                    defined.contains(segment),
                    "docs/CONFORMANCE.md cites `{token}`, but this crate declares no `{segment}`"
                );
            }
        }
    }
    assert!(
        checked > 150,
        "the matrix's API column resolved only {checked} items; it is not the map it claims to be"
    );
}

/// Is `token` shaped like a Rust path (`a`, `a::b`, `A::b_c`) rather than
/// prose, a URI, a crate name with a hyphen, or a JSON snippet?
fn is_rust_path(token: &str) -> bool {
    !token.is_empty()
        && token.split("::").all(|segment| {
            !segment.is_empty()
                && segment.starts_with(|c: char| c.is_alphabetic() || c == '_')
                && segment.chars().all(|c| c.is_alphanumeric() || c == '_')
        })
}

/// Does `name` look like one of this crate's test functions (TDD_PLAN §5's
/// naming convention: a spec-prefixed, snake-case identifier)?
fn is_test_name(name: &str) -> bool {
    ["req_", "rec_", "conf_", "per_"]
        .iter()
        .any(|prefix| name.starts_with(prefix))
        && name
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
}
